### ISSUE TITLE
Image download error 

### ISSUE THREAD

**Issue by DXIVisreal** [nekomangaorg/Neko#1847]
### Steps to reproduce

When trying to download cover it says "error saving cover" and after trying to download any of manga pages it crashes with this error.
![22yv7zc0qp7d1](https://github.com/nekomangaorg/Neko/assets/173366244/b28d1d5f-c643-4372-b613-2144a3a26497)

### Expected behavior

Saving images into specified derictory

### Actual behavior

Crash or popup error massage

### Crash logs

App version: 2.16.7 (standard, 909da0971, 8, 2024-05-14T17:29:28.138534892)
Android version: 10 (SDK 29)
Android build ID: HRY-LX1T 10.0.0.212(C10E3R1P3)
Device brand: HONOR
Device manufacturer: HUAWEI
Device name: HWHRY-HF
Device model: HRY-LX1T
Device product name: HRY-LX1TRU
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.NullPointerException
at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveImage(SourceFile:30)
at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$saveImage(SourceFile:5)
at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:8)
at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:9)
at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:3)
at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:4)
at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(SourceFile:221)
at me.saket.cascade.ToolbarKt$$ExternalSyntheticLambda0.onClick(SourceFile:238)
at android.view.View.performClick(View.java:7317)
at android.view.View.performClickInternal(View.java:7291)
at android.view.View.access$3600(View.java:838)
at android.view.View$PerformClick.run(View.java:28247)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8676)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of main
06-20 14:17:10.611 11608 11608 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:17:10.622 11608 11608 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:17:47.139 11608 11608 E RtgSchedManager: endActivityTransaction: margin state not match
--------- beginning of crash
06-20 14:18:18.818 11608 11608 E AndroidRuntime: FATAL EXCEPTION: main
06-20 14:18:18.818 11608 11608 E AndroidRuntime: Process: org.nekomanga.neko, PID: 11608
06-20 14:18:18.818 11608 11608 E AndroidRuntime: java.lang.NullPointerException
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveImage(SourceFile:30)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$saveImage(SourceFile:5)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:8)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:9)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:3)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:4)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(SourceFile:221)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at me.saket.cascade.ToolbarKt$$ExternalSyntheticLambda0.onClick(SourceFile:238)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.view.View.performClick(View.java:7317)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7291)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.view.View.access$3600(View.java:838)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28247)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8676)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-20 14:18:18.818 11608 11608 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
06-20 14:18:19.125 15354 15354 E o:error_handle: LoadAppImageStartupCache enabled : 1
06-20 14:18:19.128 15354 15354 E o:error_handle: Not starting debugger since process cannot load the jdwp agent.
06-20 14:18:19.161 15354 15372 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
06-20 14:18:23.900 15434 15434 E .nekomanga.nek: LoadAppImageStartupCache enabled : 1
06-20 14:18:23.904 15434 15434 E .nekomanga.nek: Not starting debugger since process cannot load the jdwp agent.
06-20 14:18:23.976 15434 15453 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
06-20 14:18:24.027 15434 15461 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@a444a5
06-20 14:18:24.738 15434 15434 E SQLiteLog: (283) recovered 390 frames from WAL file /data/data/org.nekomanga.neko/databases/tachiyomi.db-wal
06-20 14:18:24.761 15434 15524 E SQLiteLog: (284) automatic index on C(manga_id)
06-20 14:18:24.762 15434 15524 E SQLiteLog: (284) automatic index on R(manga_id)
06-20 14:18:24.762 15434 15524 E SQLiteLog: (284) automatic index on B(manga_id)
06-20 14:18:24.762 15434 15524 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-20 14:18:25.397 15434 15434 E HwViewGroupImpl: parse speed value length error
06-20 14:18:27.741 15434 15553 E SQLiteLog: (284) automatic index on mangas(_id)
06-20 14:18:29.647 15434 15555 E SQLiteLog: (284) automatic index on mangas(_id)
06-20 14:18:32.657 15434 15553 E SQLiteLog: (284) automatic index on mangas(_id)
06-20 14:20:34.796 15434 15434 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:20:46.644 15434 15434 E AndroidRuntime: FATAL EXCEPTION: main
06-20 14:20:46.644 15434 15434 E AndroidRuntime: Process: org.nekomanga.neko, PID: 15434
06-20 14:20:46.644 15434 15434 E AndroidRuntime: java.lang.NullPointerException
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveImage(SourceFile:30)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$saveImage(SourceFile:5)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:8)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:9)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:3)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:4)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(SourceFile:221)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at me.saket.cascade.ToolbarKt$$ExternalSyntheticLambda0.onClick(SourceFile:238)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.view.View.performClick(View.java:7317)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7291)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.view.View.access$3600(View.java:838)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28247)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8676)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-20 14:20:46.644 15434 15434 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
06-20 14:20:53.484 16428 16428 E .nekomanga.nek: LoadAppImageStartupCache enabled : 1
06-20 14:20:53.487 16428 16428 E .nekomanga.nek: Not starting debugger since process cannot load the jdwp agent.
06-20 14:20:53.521 16428 16446 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
06-20 14:20:53.576 16428 16449 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@a444a5
06-20 14:20:54.334 16428 16428 E SQLiteLog: (283) recovered 17 frames from WAL file /data/data/org.nekomanga.neko/databases/tachiyomi.db-wal
06-20 14:20:54.413 16428 16489 E SQLiteLog: (284) automatic index on C(manga_id)
06-20 14:20:54.413 16428 16489 E SQLiteLog: (284) automatic index on R(manga_id)
06-20 14:20:54.413 16428 16489 E SQLiteLog: (284) automatic index on B(manga_id)
06-20 14:20:54.413 16428 16489 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-20 14:20:55.043 16428 16428 E HwViewGroupImpl: parse speed value length error
06-20 14:20:56.385 16428 16524 E SQLiteLog: (284) automatic index on mangas(_id)
06-20 14:22:07.993 16428 16428 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:22:18.150 16428 16428 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
06-20 14:22:18.156 16428 16428 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
06-20 14:22:19.452 16428 16428 E InputMethodManager: closeCurrentInput
06-20 14:23:17.088 16428 16428 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:23:23.614 16428 16428 E AndroidRuntime: FATAL EXCEPTION: main
06-20 14:23:23.614 16428 16428 E AndroidRuntime: Process: org.nekomanga.neko, PID: 16428
06-20 14:23:23.614 16428 16428 E AndroidRuntime: java.lang.NullPointerException
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveImage(SourceFile:30)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$saveImage(SourceFile:5)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:8)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:9)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:3)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:4)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(SourceFile:221)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at me.saket.cascade.ToolbarKt$$ExternalSyntheticLambda0.onClick(SourceFile:238)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.view.View.performClick(View.java:7317)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7291)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.view.View.access$3600(View.java:838)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28247)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8676)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-20 14:23:23.614 16428 16428 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
06-20 14:26:09.145 18315 18315 E .nekomanga.nek: LoadAppImageStartupCache enabled : 1
06-20 14:26:09.149 18315 18315 E .nekomanga.nek: Not starting debugger since process cannot load the jdwp agent.
06-20 14:26:09.194 18315 18335 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
06-20 14:26:09.271 18315 18341 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@f79b07a
06-20 14:26:10.008 18315 18315 E SQLiteLog: (283) recovered 11 frames from WAL file /data/data/org.nekomanga.neko/databases/tachiyomi.db-wal
06-20 14:26:10.027 18315 18383 E SQLiteLog: (284) automatic index on C(manga_id)
06-20 14:26:10.028 18315 18383 E SQLiteLog: (284) automatic index on R(manga_id)
06-20 14:26:10.028 18315 18383 E SQLiteLog: (284) automatic index on B(manga_id)
06-20 14:26:10.028 18315 18383 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-20 14:26:10.704 18315 18315 E HwViewGroupImpl: parse speed value length error
06-20 14:26:17.871 18315 18427 E SQLiteLog: (284) automatic index on mangas(_id)
06-20 14:26:27.923 18315 18315 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:27:21.216 18315 18315 E RtgSchedManager: endActivityTransaction: margin state not match
06-20 14:27:28.601 18315 18315 E AndroidRuntime: FATAL EXCEPTION: main
06-20 14:27:28.601 18315 18315 E AndroidRuntime: Process: org.nekomanga.neko, PID: 18315
06-20 14:27:28.601 18315 18315 E AndroidRuntime: java.lang.NullPointerException
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveImage(SourceFile:30)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$saveImage(SourceFile:5)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:8)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onPageLongTap$1.invoke(SourceFile:9)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:3)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.MaterialMenuSheet$3.invoke(SourceFile:4)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at com.mikepenz.fastadapter.FastAdapter$viewClickListener$1.onClick(SourceFile:221)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at me.saket.cascade.ToolbarKt$$ExternalSyntheticLambda0.onClick(SourceFile:238)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.view.View.performClick(View.java:7317)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7291)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.view.View.access$3600(View.java:838)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28247)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8676)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-20 14:27:28.601 18315 18315 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### Neko version

2.16.7

### Android version

10

### Device

HONOR 10i

### Other details

Thought it's problem with mangadex site being blocked, but after trying vpn nothing changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Can you let me know what page,chapter, manga gave this error?

**Comment by DXIVisreal** [comment]
Everywhere. Any title and page.

**Comment by Mikrz** [comment]
I'd like to toss in that it also happens on MangaPlus titles, like Ruri Dragon for example.

**Comment by nonproto** [comment]
> I'd like to toss in that it also happens on MangaPlus titles, like Ruri Dragon for example.
> 
> I also tried to enable verbose logging and check the logcat output, but got very little output. Not sure if that's my fault or not though, I only had access to a Shizuku based logcat output via Termux, rather than a computer.

This is unrelated and likely fixed in #1848

**Comment by nonproto** [comment]
Can you try repicking your storage location in settings?

**Comment by DXIVisreal** [comment]
On 2.16.7, after i changed save directory, i can freely download pages, but still unable to download any covers. No crash but just popup massage saying "Error saving cover". That's how it works when i was installed latest version apk from github page directly. 

Right now i installed an update from 2.16.6 to 2.16.7 from the About page and somehow everything working fine. at least i dont see any errors that occured before. 

I'll try redownload apk from github to test it

**Comment by DXIVisreal** [comment]
Just installed latest apk from releases page. Everything fixed
