### ISSUE TITLE
Pages Take Extremely Long to Load or Time Out

### ISSUE THREAD

**Issue by sedorr** [nekomangaorg/Neko#2070]
### Steps to reproduce

1. Open Neko and navigate to a title.
2. Attempt to read a chapter.
3. Observe the loading times for pages.

### Expected behavior

Pages should load quickly, similar to the experience on MangaDex through the browser (Firefox for Android).

### Actual behavior

Pages take an extremely long time to load or fail to load entirely.

### Crash logs

```
App version: 2.19.4 (standard, 3ab8faa3e, 22, 2025-02-10T18:40:33.392298662)
Android version: 15 (SDK 35)
Android build ID: BP1A.250305.019
Device brand: google
Device manufacturer: Google
Device name: lynx
Device model: Pixel 7a
Device product name: lynx--------- beginning of system
03-18 00:33:50.148  5910  5910 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
03-18 00:33:55.401  5910  5910 D InsetsController: Setting requestedVisibleTypes to -9 (was -1)
03-18 00:34:08.591 23495 23495 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:36:55.113 23495 23495 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
03-18 00:36:59.329 23495 23495 D InsetsController: Setting requestedVisibleTypes to -9 (was -1)
03-18 00:37:58.610 24141 24141 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:40:55.609 24141 24141 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:41:05.211 24141 24141 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
03-18 00:41:09.981 24141 24141 D InsetsController: Setting requestedVisibleTypes to -9 (was -1)
03-18 00:41:49.994 25001 25001 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:43:10.437 25001 25001 D InsetsController: Setting requestedVisibleTypes to -9 (was -16)
--------- beginning of main
03-18 00:46:13.969 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:13.969 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:13.976 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:46:13.977 25001 25001 I ImeTracker: org.nekomanga.neko:805fa82b: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:46:14.735 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:46:14.735 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:46:14.740 25001 25001 I ImeTracker: org.nekomanga.neko:2ab49bcd: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
03-18 00:46:14.740 25001 25001 D InsetsController: show(ime(), fromIme=false)
03-18 00:46:14.741 25001 25001 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
03-18 00:46:15.066 25001 25001 W HWUI    : Image decoding logging dropped!
03-18 00:46:15.067 25001 25001 W HWUI    : Image decoding logging dropped!
03-18 00:46:15.069 25001 25001 W HWUI    : Image decoding logging dropped!
03-18 00:46:15.071 25001 25001 I Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
03-18 00:46:15.084 25001 25001 I AssistStructure: Flattened final assist data: 4864 bytes, containing 1 windows, 40 views
03-18 00:46:15.189 25001 25004 I .nekomanga.neko: Compiler allocated 6153KB to compile androidx.preference.PreferenceScreen eu.kanade.tachiyomi.ui.setting.SettingsReaderController.setupPreferenceScreen(androidx.preference.PreferenceScreen)
03-18 00:46:15.381 25001 25001 I ImeTracker: org.nekomanga.neko:2ab49bcd: onShown
03-18 00:46:22.464 25001 25001 I ImeTracker: org.nekomanga.neko:f757bce5: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
03-18 00:46:22.465 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:46:22.465 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.view.ImeBackAnimationController@1d7969b
03-18 00:46:22.465 25001 25001 D InsetsController: Setting requestedVisibleTypes to -9 (was -1)
03-18 00:46:22.466 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:46:22.466 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:46:22.478 25001 25001 I ImeTracker: org.nekomanga.neko:d301ef0c: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_CLOSE_CURRENT_SESSION fromUser false
03-18 00:46:22.478 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:46:22.479 25001 25001 I ImeTracker: org.nekomanga.neko:d301ef0c: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:46:22.509 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.510 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:46:22.806 25001 25001 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 199901530
03-18 00:46:23.647 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@b9a4737
03-18 00:46:23.771 25001 25902 W CursorWindow: Window is full: requested allocation 256 bytes, free space 145 bytes, window size 2097152 bytes
03-18 00:46:23.897 25001 25902 W CursorWindow: Window is full: requested allocation 504 bytes, free space 171 bytes, window size 2097152 bytes
03-18 00:46:24.806 25001 25045 W CursorWindow: Window is full: requested allocation 626 bytes, free space 476 bytes, window size 2097152 bytes
03-18 00:46:24.981 25001 27568 W HWUI    : Image decoding logging dropped!
03-18 00:46:24.991 25001 25902 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.001 25001 27577 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.005 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.006 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.007 25001 27570 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.010 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.011 25001 27562 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.015 25001 25050 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.016 25001 27560 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.021 25001 27568 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.022 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.031 25001 25050 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.031 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.041 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:25.049 25001 25050 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.543 25001 25020 D SessionLifecycleClient: Sending lifecycle 2 to service
03-18 00:46:28.543 25001 25070 D SessionLifecycleService: Activity backgrounding at 758936675
03-18 00:46:28.573 25001 25001 I ContentCaptureHelper: Setting logging level to OFF
03-18 00:46:28.573 25001 25017 D SessionLifecycleClient: Sending lifecycle 1 to service
03-18 00:46:28.573 25001 25070 D SessionLifecycleService: Activity foregrounding at 758936706.
03-18 00:46:28.574 25001 25001 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:46:28.627 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.643 25001 27567 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.671 25001 27567 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.672 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.685 25001 27567 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.691 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.715 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.722 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:28.732 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:46:28.732 25001 25001 I ImeTracker: org.nekomanga.neko:a25f1a6e: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:46:28.748 25001 27567 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.074 25001 27567 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.101 25001 25001 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-18 00:46:29.103 25001 25001 I AutofillManager: onInvisibleForAutofill(): expiringResponse
03-18 00:46:29.110 25001 25053 D HWUI    : endAllActiveAnimators on 0xb400007d520943b0 (UnprojectedRipple) with handle 0xb400007cb1cb7e30
03-18 00:46:29.158 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.253 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.365 25001 27563 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.533 25001 27571 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.585 25001 27564 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.648 25001 27571 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.825 25001 27571 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.881 25001 27571 W HWUI    : Image decoding logging dropped!
03-18 00:46:29.972 25001 27565 W HWUI    : Image decoding logging dropped!
03-18 00:46:30.020 25001 27565 W HWUI    : Image decoding logging dropped!
03-18 00:47:31.238 25001 25001 D InsetsController: Setting requestedVisibleTypes to -9 (was -16)
03-18 00:47:32.087 25001 25022 D SessionLifecycleClient: Sending lifecycle 2 to service
03-18 00:47:32.088 25001 25070 D SessionLifecycleService: Activity backgrounding at 759000220
03-18 00:47:32.095 25001 25022 D SessionLifecycleClient: Sending lifecycle 1 to service
03-18 00:47:32.095 25001 25070 D SessionLifecycleService: Activity foregrounding at 759000228.
03-18 00:47:32.146 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:47:32.146 25001 25001 I ImeTracker: org.nekomanga.neko:41a708ab: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:47:32.250 25001 27571 W CursorWindow: Window is full: requested allocation 626 bytes, free space 476 bytes, window size 2097152 bytes
03-18 00:47:32.465 25001 25001 D VRI[ReaderActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-18 00:47:32.475 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.app.Activity$$ExternalSyntheticLambda0@35e2df4
03-18 00:47:32.478 25001 25001 D ViewRootImpl: Skipping stats log for color mode
03-18 00:47:34.463 25001 25001 W HWUI    : Image decoding logging dropped!
03-18 00:47:34.464 25001 25001 W HWUI    : Image decoding logging dropped!
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.494 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.495 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.495 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.495 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.495 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.495 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:34.807 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.compose.ui.window.Api33Impl$$ExternalSyntheticLambda0@1aaa4ec
03-18 00:47:34.813 25001 25053 D HWUI    : endAllActiveAnimators on 0xb400007d51fe8d50 (UnprojectedRipple) with handle 0xb400007cb1cbb820
03-18 00:47:35.125 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:47:35.128 25001 25001 I ImeTracker: org.nekomanga.neko:d535692d: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
03-18 00:47:35.128 25001 25001 D InsetsController: show(ime(), fromIme=false)
03-18 00:47:35.129 25001 25001 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
03-18 00:47:35.613 25001 25001 I ImeTracker: org.nekomanga.neko:d535692d: onShown
03-18 00:47:37.943 25001 25001 I ImeTracker: org.nekomanga.neko:6a081ed3: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
03-18 00:47:37.943 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:47:37.943 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=android.view.ImeBackAnimationController@1d7969b
03-18 00:47:37.943 25001 25001 D InsetsController: Setting requestedVisibleTypes to -9 (was -1)
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.120 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:38.121 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:52.976 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:56.334 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:56.644 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:57.075 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:58.040 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:58.361 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:47:58.671 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:00.599 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:00.909 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:12.882 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:13.003 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:13.037 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:13.114 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:13.207 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:13.349 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:14.223 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:17.891 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:21.495 25001 25001 I ImeTracker: org.nekomanga.neko:ea02ad52: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
03-18 00:48:21.495 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:48:21.495 25001 25001 I ImeTracker: org.nekomanga.neko:ea02ad52: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:48:22.431 25001 25001 I ImeTracker: org.nekomanga.neko:72e831ad: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
03-18 00:48:22.432 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:48:22.432 25001 25001 I ImeTracker: org.nekomanga.neko:72e831ad: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:48:22.432 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:48:22.432 25001 25001 D AutofillManager: view not autofillable - not passing ime action check
03-18 00:48:22.442 25001 25001 I ImeTracker: org.nekomanga.neko:a041a750: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_CLOSE_CURRENT_SESSION fromUser false
03-18 00:48:22.443 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:48:22.443 25001 25001 I ImeTracker: org.nekomanga.neko:a041a750: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.477 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.478 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.478 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.478 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:22.478 25001 25001 E .nekomanga.neko: Invalid resource ID 0x00000000.
03-18 00:48:23.173 25001 25001 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@b9a4737
03-18 00:48:23.191 25001 25001 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
03-18 00:48:23.365 25001 27692 W CursorWindow: Window is full: requested allocation 626 bytes, free space 476 bytes, window size 2097152 bytes
03-18 00:48:26.858 25001 25001 W Choreographer: Frame time is 0.112247996 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
03-18 00:48:26.970 25001 25022 D SessionLifecycleClient: Sending lifecycle 2 to service
03-18 00:48:26.970 25001 25070 D SessionLifecycleService: Activity backgrounding at 759055102
03-18 00:48:26.993 25001 25001 I ContentCaptureHelper: Setting logging level to OFF
03-18 00:48:26.993 25001 25019 D SessionLifecycleClient: Sending lifecycle 1 to service
03-18 00:48:26.994 25001 25070 D SessionLifecycleService: Activity foregrounding at 759055126.
03-18 00:48:26.995 25001 25001 D InsetsController: Setting requestedVisibleTypes to -16 (was -9)
03-18 00:48:27.068 25001 27561 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.096 25001 27694 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.099 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.118 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.141 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.149 25001 25001 D InsetsController: hide(ime(), fromIme=false)
03-18 00:48:27.149 25001 25001 I ImeTracker: org.nekomanga.neko:dff5d3be: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
03-18 00:48:27.163 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.474 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.526 25001 25001 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
03-18 00:48:27.529 25001 25001 I AutofillManager: onInvisibleForAutofill(): expiringResponse
03-18 00:48:27.537 25001 25053 D HWUI    : endAllActiveAnimators on 0xb400007d51f32920 (RippleDrawable) with handle 0xb400007cb1cc5e10
03-18 00:48:27.537 25001 25053 D HWUI    : endAllActiveAnimators on 0xb400007d5223a4a0 (UnprojectedRipple) with handle 0xb400007cb1cc8960
03-18 00:48:27.547 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.638 25001 27692 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.744 25001 27692 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.902 25001 27690 W HWUI    : Image decoding logging dropped!
03-18 00:48:27.958 25001 27692 W 

```
### Neko version

2.19.4

### Android version

Android 15 (BP1A.250305.019)

### Device

Google Pixel 7a 

### Other details

- Enabling DNS over HTTPS did not help.
- Cleared cookies and app cache, but the issue persists.
- Being signed in or not made no difference; the issue persists in both cases.
- Other interactions with MangaDex, such as browsing, searching for titles, and updating the library, work without issue. Only page loading seems to be affected.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [x] I have filled out all of the requested information in this form.

**Comment by theresnobio** [comment]
This may be it
https://status.mangadex.org/

**Comment by sedorr** [comment]
Seems so, because it stopped happening, but it's weird that it only affected neko for me...

**Comment by theresnobio** [comment]
It actually affected me with the downloads and was just recently told. You can see my issue if you want

**Comment by nonproto** [comment]
This should be resolved

**Comment by Roxyxninjas** [comment]
I've had this same issue happening ever since yesterday evening and its still happening. Do I need to do something or?

**Comment by Roxyxninjas** [comment]
I don't understand why it's not working, please give me some advice because it's happening on both my phone, Motorola Razr 2024, and my tablet, Samsung Galaxy A Tab Plus,> This should be resolved

**Comment by nonproto** [comment]
Update your app

**Comment by Roxyxninjas** [comment]
I don't know why but it's happening a bit with this new update as well. It's like some pages from yesterday after the update would work sometimes but everything after that won't even come close to loading

**Comment by shakey2** [comment]
Updated to 2.19.5

Bug is still happening as described in original issue. With pages not loading. Chapters not downloading. Chapters can be read on website without issue at the time the bug is occurring.

[neko_crash_log-202503301026.txt](https://github.com/user-attachments/files/19526988/neko_crash_log-202503301026.txt)

**Comment by nonproto** [comment]
The issue seems to be on the mangadex side now. It took someone on discord over 5 mins to load a page in a browser

**Comment by shakey2** [comment]
Strange 🤔 I switched to reading on site at the time. Maybe it was just timing.

**Comment by TylerWDoesStuff** [comment]
I feel like it is also timing - app doesn't load but website does, earlier neither were loading - but why would the results be different between website and (presumably) API? In theory, the CDNs are the same, but website loads pages instantly while app just spins.
