### ISSUE TITLE
Reading in webtoon mode chapters are backwards.

### ISSUE THREAD

**Issue by Numnut64** [nekomangaorg/Neko#2450]
### Steps to reproduce

1. Set reading mode to webtoon.
2. Reach the end of a chapter.
3. Going further loads the previous chapter.

### Expected behavior

Instead of loading the previous chapter it should load the next chapter.

### Actual behavior

When scrolling to the next chapter it loads the previous chapter.

### Neko version

3.1.2

### Android version

Android 12

### Device

Lenovo legion tab Y700 - Lenovo TB-9707F

### Other details

Only stated happening since the latest update.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [x] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Couple questions.

1.  can you attach a screenshot of your sort mode in the manga details screen
2. can you attach a screenshot of chapter list in the reader

**Comment by Numnut64** [comment]
No problem, here you go.

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/71ad6194-0fc9-4752-8041-f43fae56bb46" />

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/3fc93a1b-374f-4b90-9a50-f451fb5de8cf" />

**Comment by nonproto** [comment]
very weird you are sure you are on 3.1.2? 

source sort with the arrow down for the same manga is showing chp 1 ... to 43.  Yours is showing how it was in the pulled 3.1.1 release

**Comment by Numnut64** [comment]
I just downloaded the new version and I set the sort that way so the new chapters appear in descending order as that how I have always had it.

Here are some more screenshots for clarity.

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/b532117f-25be-4bf1-812f-741d652d8ec3" />

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/a3e15a5d-ffe8-48bc-a64e-415da534875c" />

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/8f487ef3-313e-4918-9aef-1050f2d473a0" />

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/7b8402a2-77af-4c26-83e7-5878f60bbf6c" />

**Comment by nonproto** [comment]
Can you try switching it to smart order, then back to source order?   Here is 3.1.2 on my phone.  Notice the ordering is different in the first screenshot but the configuration is the same in the 2nd 

<img width="728" height="1503" alt="Image" src="https://github.com/user-attachments/assets/2c406830-890b-455c-8de8-2b62840741de" />

<img width="726" height="1503" alt="Image" src="https://github.com/user-attachments/assets/665efba2-6d10-4f74-a0f6-93c65ba26050" />

**Comment by Numnut64** [comment]
I tried doing what you said but I don't seem to get the same effect but I did try reading while the sort was set to smart and the chapter did load in the correct order.

Here I am switching between the two.

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/e72464d7-49bb-451c-9c04-fd1e2e3dcfe7" />

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/d67e038e-61cd-4cf6-8804-2eadfc9ff842" />

And this is how chapters load when set to smart sort.

<img width="1600" height="2560" alt="Image" src="https://github.com/user-attachments/assets/691b9fdd-3203-4e2d-ab43-f763d1841497" />

**Comment by nonproto** [comment]
I guess for now use smart order its the best intended order.  I can't quite replicate why your source order is flipped, so i cant really fix this as it works on my end it.  I'll leave this open and hopefully something happens and it can be adjusted in future

**Comment by ResidentNintendoNerd** [comment]
![Image](https://github.com/user-attachments/assets/27b834df-58ae-46f8-b6bf-b52c037ce45d)
+1, but for normal manga mode as well, the chapters are in reverse order (source's order mode selected) and when scrolling to the "next" chapter, it goes to the previous chapter instead

Edit:
![Image](https://github.com/user-attachments/assets/069a3a91-f3ce-462d-94c1-00f92d68483a)
The "Continue reading" button also displays the incorrect chapter, linking to the latest chapter instead of the next unread chapter (I've only read to chapter 2 so far)

**Comment by nonproto** [comment]
Should be resolved in 3.1.3

**Comment by ResidentNintendoNerd** [comment]
Still not resolved on version 3.1.3 (note the "Next" chapter being before the "Finished" chapter)
![Image](https://github.com/user-attachments/assets/0cc12935-1dae-43f0-bfdb-af6246168c40)

![Image](https://github.com/user-attachments/assets/716b1406-a1f6-4538-b0fd-48d7b26c0d59)

**Comment by nonproto** [comment]
That seems to be an issue due to the volume number. What does the order look like in manga chapter list

**Comment by ResidentNintendoNerd** [comment]
Sort order is set to "↓ Source's order"
![Image](https://github.com/user-attachments/assets/bd837383-fb8f-452c-b92c-a2839f096375)

Note that this happens regardless of a volume number being present or what it is. See:

![Image](https://github.com/user-attachments/assets/8b8cdccf-83d6-4537-bc65-63dc070eb0d2)

![Image](https://github.com/user-attachments/assets/90d2a5b8-b6ab-4387-9697-0be070b86015)

**Comment by nonproto** [comment]
![Screenshot_20251027-144631.png](https://github.com/user-attachments/assets/eca03bbb-85aa-40d1-9490-11efa90aa966)

Source arrow down for me 😅

Few different things to try if the step doesn't work go to the next step

1.  Swipe refresh the manga
2.  Backup and clear the storage the data for the app then restore the backup

**Comment by ResidentNintendoNerd** [comment]
Oh, swipe refreshing it fixed it, I guess it'll fully fix itself on the next library update then lol
